// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnpmjqrivssgpexjchvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucG1qcXJpdnNzZ3BleGpjaHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjQ0NTIsImV4cCI6MjA2NjcwMDQ1Mn0.9e_c5-1-lAx4mB0LVSjojqlzGZmJlGy1TzKqdqP3F6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});