// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jihntuehqlyvzzkihlsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaG50dWVocWx5dnp6a2lobHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTcxNTgsImV4cCI6MjA2Njg3MzE1OH0.OxEYeaJ4g_PXduPJ636CgjjferHBgN6hz-AZAiCnHks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});